name: Deploy Backstage

on:
  push:
    branches:
      - master
      
env:
  environment: production
  NODE_OPTIONS: --no-node-snapshot
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run yarn tsc
        uses: borales/actions-yarn@v4
        with:
          cmd: tsc

      - name: Run yarn Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build:backend
      - name: Set up QEMU ğŸ› ï¸
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx ğŸ› ï¸
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Registry ğŸªª
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker ğŸš€
        uses: docker/build-push-action@v5
        with:
          push: true
          file: packages/backend/Dockerfile
          tags: imyashkale/the-idp
          context: .
          platforms: linux/amd64,linux/arm64
