name: Deploy Backstage

on:
  push:
    branches:
      - master
      
env:
  environment: production
  NODE_OPTIONS: --no-node-snapshot
jobs:
  deploy:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set Node.js 18
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18
          cache: 'yarn'

      - name: Run install
        run: yarn install

      - name: Run yarn tsc
        run: yarn tsc

      - name: Run yarn Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build:backend

      - name: Set up QEMU ğŸ› ï¸
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx ğŸ› ï¸
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login Docker Registry ğŸªª
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker ğŸš€
        uses: docker/build-push-action@v5
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: packages/backend/Dockerfile
          tags: imyashkale/the-idp
          context: .
          platforms: linux/amd64,linux/arm64
