name: Deploy Backstage

on:
  push:
    branches:
      - master
      
env:
  environment: production
  NODE_OPTIONS: --no-node-snapshot
jobs:
  deploy:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set Node.js 20.12.2
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.12.2
          cache: 'yarn'

      - name: Run install
        run: yarn install

      - name: Run yarn tsc
        run: yarn tsc
      
      - name: Run yarn build
        run: yarn build:backend

      - name: Set up QEMU ğŸ› ï¸
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx ğŸ› ï¸
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login Docker Registry ğŸªª
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: yarn build-image
